// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO9143ynIbDarDyv_xmTkrIwzrogVpIDQ',
    appId: '1:498038086127:web:39f1601c90698648cafe1a',
    messagingSenderId: '498038086127',
    projectId: 'rt-test-7ad2e',
    authDomain: 'rt-test-7ad2e.firebaseapp.com',
    storageBucket: 'rt-test-7ad2e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzE8jfxqvwKYE8Kd4ABHJX6mHlwsQYLi4',
    appId: '1:498038086127:android:2fd9a809e2878f4ccafe1a',
    messagingSenderId: '498038086127',
    projectId: 'rt-test-7ad2e',
    storageBucket: 'rt-test-7ad2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHHuPZg-jaFXs_J0EGU6bFQF1G32sM6Aw',
    appId: '1:498038086127:ios:cee74313cfc29aa4cafe1a',
    messagingSenderId: '498038086127',
    projectId: 'rt-test-7ad2e',
    storageBucket: 'rt-test-7ad2e.appspot.com',
    iosClientId: '498038086127-tf8l9r4b81uaublj4sps7a8dc114tnlo.apps.googleusercontent.com',
    iosBundleId: 'com.example.rt2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHHuPZg-jaFXs_J0EGU6bFQF1G32sM6Aw',
    appId: '1:498038086127:ios:cee74313cfc29aa4cafe1a',
    messagingSenderId: '498038086127',
    projectId: 'rt-test-7ad2e',
    storageBucket: 'rt-test-7ad2e.appspot.com',
    iosClientId: '498038086127-tf8l9r4b81uaublj4sps7a8dc114tnlo.apps.googleusercontent.com',
    iosBundleId: 'com.example.rt2',
  );
}
